import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ReduxProvider } from '../redux/ReduxProvider'
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api'
import { ThemeProvider, createTheme } from '@mui/material/styles'
import Navbar from '@/components/NavBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
